//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOTHMASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOTHMASTER()
        {
            this.PERSONINFOes = new HashSet<PERSONINFO>();
            this.SOCIETYMASTERs = new HashSet<SOCIETYMASTER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> WARD_ID { get; set; }
        public Nullable<int> MATDAN_ID { get; set; }
        public Nullable<int> BOOTH1 { get; set; }
        public Nullable<int> BOOTH2 { get; set; }
        public Nullable<int> BOOTH3 { get; set; }
        public Nullable<int> BOOTH4 { get; set; }
        public Nullable<int> BOOTH5 { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<bool> EF1 { get; set; }
        public Nullable<bool> EF2 { get; set; }
        public Nullable<bool> EF3 { get; set; }
        public Nullable<bool> EF4 { get; set; }
        public Nullable<bool> EF5 { get; set; }
    
        public virtual MATDANMATHAKMASTER MATDANMATHAKMASTER { get; set; }
        public virtual USERMASTER USERMASTER { get; set; }
        public virtual WARDMASTER WARDMASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONINFO> PERSONINFOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOCIETYMASTER> SOCIETYMASTERs { get; set; }
    }
}
