//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONINFO
    {
        public int ID { get; set; }
        public string UNIQUE_NUMBER { get; set; }
        public string VOTER_ID { get; set; }
        public string NAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> AGE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> WARD_ID { get; set; }
        public Nullable<int> MATDAN_ID { get; set; }
        public Nullable<int> BOOTH_ID { get; set; }
        public Nullable<int> SOCIETY_ID { get; set; }
        public Nullable<bool> ISVOTED { get; set; }
        public Nullable<System.DateTime> VOTE_TIMESTAMP { get; set; }
        public Nullable<bool> EF1 { get; set; }
        public Nullable<bool> EF2 { get; set; }
        public Nullable<bool> EF3 { get; set; }
        public Nullable<bool> EF4 { get; set; }
        public Nullable<bool> EF5 { get; set; }
    
        public virtual BOOTHMASTER BOOTHMASTER { get; set; }
        public virtual MATDANMATHAKMASTER MATDANMATHAKMASTER { get; set; }
        public virtual SOCIETYMASTER SOCIETYMASTER { get; set; }
        public virtual WARDMASTER WARDMASTER { get; set; }
    }
}
