//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCEMASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESOURCEMASTER()
        {
            this.RIGHTMASTERs = new HashSet<RIGHTMASTER>();
        }
    
        public int ID { get; set; }
        public string RESOURCE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIGHTMASTER> RIGHTMASTERs { get; set; }
    }
}
