//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIGHTMASTER
    {
        public int ID { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<int> RESOURCE_ID { get; set; }
        public Nullable<bool> ISADD { get; set; }
        public Nullable<bool> ISUPDATE { get; set; }
        public Nullable<bool> ISVIEW { get; set; }
        public Nullable<bool> ISPRINT { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual RESOURCEMASTER RESOURCEMASTER { get; set; }
        public virtual RIGHTMASTER RIGHTMASTER1 { get; set; }
        public virtual RIGHTMASTER RIGHTMASTER2 { get; set; }
        public virtual ROLEMASTER ROLEMASTER { get; set; }
    }
}
