//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARDMASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WARDMASTER()
        {
            this.BOOTHMASTERs = new HashSet<BOOTHMASTER>();
            this.MATDANMATHAKMASTERs = new HashSet<MATDANMATHAKMASTER>();
            this.PERSONINFOes = new HashSet<PERSONINFO>();
            this.SOCIETYMASTERs = new HashSet<SOCIETYMASTER>();
        }
    
        public int ID { get; set; }
        public string WARDNAME { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<bool> EF1 { get; set; }
        public Nullable<bool> EF2 { get; set; }
        public Nullable<bool> EF3 { get; set; }
        public Nullable<bool> EF4 { get; set; }
        public Nullable<bool> EF5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOTHMASTER> BOOTHMASTERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATDANMATHAKMASTER> MATDANMATHAKMASTERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONINFO> PERSONINFOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOCIETYMASTER> SOCIETYMASTERs { get; set; }
        public virtual USERMASTER USERMASTER { get; set; }
    }
}
