//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WMEntities : DbContext
    {
        public WMEntities()
            : base("name=WMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOTHMASTER> BOOTHMASTERs { get; set; }
        public virtual DbSet<MATDANMATHAKMASTER> MATDANMATHAKMASTERs { get; set; }
        public virtual DbSet<PERSONINFO> PERSONINFOes { get; set; }
        public virtual DbSet<RESOURCEMASTER> RESOURCEMASTERs { get; set; }
        public virtual DbSet<RIGHTMASTER> RIGHTMASTERs { get; set; }
        public virtual DbSet<ROLEMASTER> ROLEMASTERs { get; set; }
        public virtual DbSet<SOCIETYMASTER> SOCIETYMASTERs { get; set; }
        public virtual DbSet<USERMASTER> USERMASTERs { get; set; }
        public virtual DbSet<WARDMASTER> WARDMASTERs { get; set; }
    
        [DbFunction("WMEntities", "FUNC_SEARCH_BOOTH")]
        public virtual IQueryable<FUNC_SEARCH_BOOTH_Result> FUNC_SEARCH_BOOTH(string searchVal, Nullable<int> primaryId)
        {
            var searchValParameter = searchVal != null ?
                new ObjectParameter("searchVal", searchVal) :
                new ObjectParameter("searchVal", typeof(string));
    
            var primaryIdParameter = primaryId.HasValue ?
                new ObjectParameter("primaryId", primaryId) :
                new ObjectParameter("primaryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_SEARCH_BOOTH_Result>("[WMEntities].[FUNC_SEARCH_BOOTH](@searchVal, @primaryId)", searchValParameter, primaryIdParameter);
        }
    
        [DbFunction("WMEntities", "FUNC_SEARCH_MATDANMATHAK")]
        public virtual IQueryable<FUNC_SEARCH_MATDANMATHAK_Result> FUNC_SEARCH_MATDANMATHAK(string searchVal, Nullable<int> primaryId, Nullable<int> wardId)
        {
            var searchValParameter = searchVal != null ?
                new ObjectParameter("searchVal", searchVal) :
                new ObjectParameter("searchVal", typeof(string));
    
            var primaryIdParameter = primaryId.HasValue ?
                new ObjectParameter("primaryId", primaryId) :
                new ObjectParameter("primaryId", typeof(int));
    
            var wardIdParameter = wardId.HasValue ?
                new ObjectParameter("wardId", wardId) :
                new ObjectParameter("wardId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_SEARCH_MATDANMATHAK_Result>("[WMEntities].[FUNC_SEARCH_MATDANMATHAK](@searchVal, @primaryId, @wardId)", searchValParameter, primaryIdParameter, wardIdParameter);
        }
    
        [DbFunction("WMEntities", "FUNC_SEARCH_PERSONINFO")]
        public virtual IQueryable<FUNC_SEARCH_PERSONINFO_Result> FUNC_SEARCH_PERSONINFO(string searchVal, Nullable<int> primaryId)
        {
            var searchValParameter = searchVal != null ?
                new ObjectParameter("searchVal", searchVal) :
                new ObjectParameter("searchVal", typeof(string));
    
            var primaryIdParameter = primaryId.HasValue ?
                new ObjectParameter("primaryId", primaryId) :
                new ObjectParameter("primaryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_SEARCH_PERSONINFO_Result>("[WMEntities].[FUNC_SEARCH_PERSONINFO](@searchVal, @primaryId)", searchValParameter, primaryIdParameter);
        }
    
        [DbFunction("WMEntities", "FUNC_SEARCH_SOCIETY")]
        public virtual IQueryable<FUNC_SEARCH_SOCIETY_Result> FUNC_SEARCH_SOCIETY(string searchVal, Nullable<int> primaryId)
        {
            var searchValParameter = searchVal != null ?
                new ObjectParameter("searchVal", searchVal) :
                new ObjectParameter("searchVal", typeof(string));
    
            var primaryIdParameter = primaryId.HasValue ?
                new ObjectParameter("primaryId", primaryId) :
                new ObjectParameter("primaryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_SEARCH_SOCIETY_Result>("[WMEntities].[FUNC_SEARCH_SOCIETY](@searchVal, @primaryId)", searchValParameter, primaryIdParameter);
        }
    
        [DbFunction("WMEntities", "FUNC_SEARCH_USERMASTER")]
        public virtual IQueryable<FUNC_SEARCH_USERMASTER_Result> FUNC_SEARCH_USERMASTER(string searchVal, Nullable<int> primaryId, Nullable<int> roleId)
        {
            var searchValParameter = searchVal != null ?
                new ObjectParameter("searchVal", searchVal) :
                new ObjectParameter("searchVal", typeof(string));
    
            var primaryIdParameter = primaryId.HasValue ?
                new ObjectParameter("primaryId", primaryId) :
                new ObjectParameter("primaryId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_SEARCH_USERMASTER_Result>("[WMEntities].[FUNC_SEARCH_USERMASTER](@searchVal, @primaryId, @roleId)", searchValParameter, primaryIdParameter, roleIdParameter);
        }
    
        [DbFunction("WMEntities", "FUNC_SEARCH_WARD")]
        public virtual IQueryable<FUNC_SEARCH_WARD_Result> FUNC_SEARCH_WARD(string searchVal, Nullable<int> primaryId)
        {
            var searchValParameter = searchVal != null ?
                new ObjectParameter("searchVal", searchVal) :
                new ObjectParameter("searchVal", typeof(string));
    
            var primaryIdParameter = primaryId.HasValue ?
                new ObjectParameter("primaryId", primaryId) :
                new ObjectParameter("primaryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_SEARCH_WARD_Result>("[WMEntities].[FUNC_SEARCH_WARD](@searchVal, @primaryId)", searchValParameter, primaryIdParameter);
        }
    
        public virtual int PROC_CREATE_RESOURCE(string rESOURCE_NAME)
        {
            var rESOURCE_NAMEParameter = rESOURCE_NAME != null ?
                new ObjectParameter("RESOURCE_NAME", rESOURCE_NAME) :
                new ObjectParameter("RESOURCE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CREATE_RESOURCE", rESOURCE_NAMEParameter);
        }
    
        public virtual ObjectResult<PROC_GET_ALL_BOOTH_Result> PROC_GET_ALL_BOOTH(Nullable<int> boothId, string searchVal)
        {
            var boothIdParameter = boothId.HasValue ?
                new ObjectParameter("boothId", boothId) :
                new ObjectParameter("boothId", typeof(int));
    
            var searchValParameter = searchVal != null ?
                new ObjectParameter("searchVal", searchVal) :
                new ObjectParameter("searchVal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_ALL_BOOTH_Result>("PROC_GET_ALL_BOOTH", boothIdParameter, searchValParameter);
        }
    
        public virtual ObjectResult<PROC_GET_ALL_MATDANMATHAK_Result> PROC_GET_ALL_MATDANMATHAK(Nullable<int> matdanId)
        {
            var matdanIdParameter = matdanId.HasValue ?
                new ObjectParameter("matdanId", matdanId) :
                new ObjectParameter("matdanId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_ALL_MATDANMATHAK_Result>("PROC_GET_ALL_MATDANMATHAK", matdanIdParameter);
        }
    
        public virtual ObjectResult<PROC_GET_VOTING_DATA_Result> PROC_GET_VOTING_DATA(string seachVal, Nullable<int> wardId, Nullable<int> matdanId, Nullable<int> boothNumber, Nullable<int> societyId)
        {
            var seachValParameter = seachVal != null ?
                new ObjectParameter("seachVal", seachVal) :
                new ObjectParameter("seachVal", typeof(string));
    
            var wardIdParameter = wardId.HasValue ?
                new ObjectParameter("wardId", wardId) :
                new ObjectParameter("wardId", typeof(int));
    
            var matdanIdParameter = matdanId.HasValue ?
                new ObjectParameter("matdanId", matdanId) :
                new ObjectParameter("matdanId", typeof(int));
    
            var boothNumberParameter = boothNumber.HasValue ?
                new ObjectParameter("boothNumber", boothNumber) :
                new ObjectParameter("boothNumber", typeof(int));
    
            var societyIdParameter = societyId.HasValue ?
                new ObjectParameter("societyId", societyId) :
                new ObjectParameter("societyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_VOTING_DATA_Result>("PROC_GET_VOTING_DATA", seachValParameter, wardIdParameter, matdanIdParameter, boothNumberParameter, societyIdParameter);
        }
    }
}
