//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WMEntities : DbContext
    {
        public WMEntities()
            : base("name=WMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOTHMASTER> BOOTHMASTERs { get; set; }
        public virtual DbSet<MATDANMATHAKMASTER> MATDANMATHAKMASTERs { get; set; }
        public virtual DbSet<ROLEMASTER> ROLEMASTERs { get; set; }
        public virtual DbSet<USERMASTER> USERMASTERs { get; set; }
        public virtual DbSet<WARDMASTER> WARDMASTERs { get; set; }
    
        [DbFunction("WMEntities", "FUNC_SEARCH_BOOTH")]
        public virtual IQueryable<FUNC_SEARCH_BOOTH_Result> FUNC_SEARCH_BOOTH(string searchVal, Nullable<int> primaryId)
        {
            var searchValParameter = searchVal != null ?
                new ObjectParameter("searchVal", searchVal) :
                new ObjectParameter("searchVal", typeof(string));
    
            var primaryIdParameter = primaryId.HasValue ?
                new ObjectParameter("primaryId", primaryId) :
                new ObjectParameter("primaryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_SEARCH_BOOTH_Result>("[WMEntities].[FUNC_SEARCH_BOOTH](@searchVal, @primaryId)", searchValParameter, primaryIdParameter);
        }
    
        [DbFunction("WMEntities", "FUNC_SEARCH_MATDANMATHAK")]
        public virtual IQueryable<FUNC_SEARCH_MATDANMATHAK_Result> FUNC_SEARCH_MATDANMATHAK(string searchVal, Nullable<int> primaryId)
        {
            var searchValParameter = searchVal != null ?
                new ObjectParameter("searchVal", searchVal) :
                new ObjectParameter("searchVal", typeof(string));
    
            var primaryIdParameter = primaryId.HasValue ?
                new ObjectParameter("primaryId", primaryId) :
                new ObjectParameter("primaryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_SEARCH_MATDANMATHAK_Result>("[WMEntities].[FUNC_SEARCH_MATDANMATHAK](@searchVal, @primaryId)", searchValParameter, primaryIdParameter);
        }
    
        [DbFunction("WMEntities", "FUNC_SEARCH_WARD")]
        public virtual IQueryable<FUNC_SEARCH_WARD_Result> FUNC_SEARCH_WARD(string searchVal, Nullable<int> primaryId)
        {
            var searchValParameter = searchVal != null ?
                new ObjectParameter("searchVal", searchVal) :
                new ObjectParameter("searchVal", typeof(string));
    
            var primaryIdParameter = primaryId.HasValue ?
                new ObjectParameter("primaryId", primaryId) :
                new ObjectParameter("primaryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_SEARCH_WARD_Result>("[WMEntities].[FUNC_SEARCH_WARD](@searchVal, @primaryId)", searchValParameter, primaryIdParameter);
        }
    }
}
